### ISSUE TITLE
Question - Dynamic BPMN loading

### ISSUE THREAD

**Issue by AmareshKulkarni** [apache/incubator-kie-examples#914] opened 2021-10-05 11:15 UTC
Assuming that we enable the online bpmn editor to let our business users create BPMN flows, is there a way to dynamically load the new business processes created? Could someone please point me to an example?

**Comment by r00ta** [comment] 2021-10-05 11:57
Hi @AmareshKulkarni , this is a duplicate of https://github.com/kiegroup/kogito-runtimes/issues/999 . 

This is not possible at the moment. I'll close this issue, feel free to comment to the issue I posted above!

**Closed as completed by r00ta** 2021-10-05 11:57 UTC

**Comment by AmareshKulkarni** [comment] 2021-10-05 11:58
Thank you for the quick response.
