### ISSUE TITLE
Can't run "ruleunit-event-driven-quarkus" tests using VSCode Test Runner for Java extension

### ISSUE THREAD

**Issue by faustool** [apache/incubator-kie-examples#1198] opened 2022-03-25 19:41 UTC
### Describe the bug

When I try to run the VSCode Test Runner

**Comment by cristianonicolai** [comment] 2022-03-30 07:20
Closing this as duplicate of https://github.com/kiegroup/kogito-examples/issues/1199

**Closed as completed by cristianonicolai** 2022-03-30 07:20 UTC
